---
title: "Acknowledgements and Funding"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Abstract, acknowledgements and funding sources for the project here.

# Abstract

Diverse crops are both outbred and clonally propagated. Breeders typically use truncation selection of parents and invest significant time, land and money evaluating the progeny of crosses to find exceptional genotypes. We developed and tested genomic mate selection criteria suitable for organisms of arbitrary homozygosity level where the full-sibling progeny are of direct interest as future parents and/or cultivars. We extended cross variance and covariance variance prediction to include dominance effects and predicted the multivariate selection index genetic variance of crosses based on haplotypes of proposed parents, marker effects and recombination frequencies. We combined the predicted mean and variance into usefulness criteria for parent and variety development. We present an empirical study of cassava (Manihot esculenta), a staple tropical root crop. We assessed the potential to predict the multivariate genetic distribution (means, variances and trait covariances) of 462 cassava families in terms of additive and total value using cross-validation. Most variance (89%) and covariance (70%) prediction accuracy estimates were greater than zero. The usefulness of crosses were accurately predicted with good correspondence between the predicted and the actual mean performance of family members breeders selected for advancement as new parents and candidate varieties.  We also used a directional dominance model to quantify significant inbreeding depression for most traits. We predicted 47,083 possible crosses of 306 parents and contrasted them to those previously tested to show how mate selection can reveal new potential within the germplasm. We enable breeders to consider the potential of crosses to produce future parents (progeny with top breeding values) and varieties (progeny with top own performance). 
performance) on a multi-trait selection index. 

# Acknowledgements

We are grateful to the entire [Next Generation Cassava Breeding team](www.nextgencassava.org) and especially the International Institute of Tropical Agriculture Cassava Breeding team, so many of whom have contributed to this study in the field, in the lab and beyond. We appreciate Christian Werner for pointing us towards directional dominance models, and the Jean-Luc Jannink and Mark Sorrells research groups for fruitful discussions and comments along the way. Thanks to Lukas Mueller and Prasad Peteti for data hosting and curation respectively. We would also like to thank three anonymous reviewers and the editor whose constructive feedback substantially improved the paper.

# Funding

We acknowledge the Bill & Melinda Gates Foundation and UK Foreign, Commonwealth & Development Office (FCDO) (Grant 1048542) and support from the CGIAR Research Program on Roots, Tubers and Bananas.

